services:
  controller:
    build:
      context: ..
      dockerfile: docker/controller.Dockerfile
    ports:
      - "9000:9000"
      - "9090:9090"
    networks:
      - sv_net

  agent-1:
    build:
      context: ..
      dockerfile: docker/agent.Dockerfile
    command: [ "controller", "9000", "1" ]
    depends_on:
      - controller
    networks:
      - sv_net

  agent-2:
    build:
      context: ..
      dockerfile: docker/agent.Dockerfile
    command: [ "controller", "9000", "2" ]
    depends_on:
      - controller
    networks:
      - sv_net

  agent-3:
    build:
      context: ..
      dockerfile: docker/agent.Dockerfile
    command: [ "controller", "9000", "3" ]
    depends_on:
      - controller
    networks:
      - sv_net

networks:
  sv_net:
